version: '3'

services: 
    bdd_users:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: users
        ports:
            - "3306:3306"
        volumes:
            - ./bdd:/docker-entrypoint-initdb.d:ro
    
    web_service:
        build:
            context: ./web_service
            dockerfile: Dockerfile
        environment: 
            FLASK_ENV: development
            FLASK_APP: app.py
        ports:
            - '5000:5000'
    
    siteweb:
        build: 
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
